name: Yacd-meta

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: ğŸ›ï¸ Checkout
      uses: actions/checkout@v4

    - name: â¬‡ï¸ Clone the Yacd-meta source code
      run: git clone --depth=1 https://github.com/MetaCubeX/Yacd-meta.git

    - name: ğŸ“¦ Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: ğŸ§° Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        cache-dependency-path: Yacd-meta/pnpm-lock.yaml

    - name: ğŸ“¥ Install dependencies
      working-directory: ./Yacd-meta
      run: pnpm i

    - name: ğŸ—ï¸ Build project
      working-directory: ./Yacd-meta
      run: pnpm build

    - name: ğŸ“¦ Zip build output
      working-directory: ./Yacd-meta
      run: zip -r dashboard.zip public/

    - name: ğŸ“¤ Upload dashboard artifact
      uses: actions/upload-artifact@v4
      with:
        name: dashboard
        path: Yacd-meta/dashboard.zip

